# Generated by Django 6.1 on 2026-08-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_remove_folder_parent_folder_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
