# Generated by Django 6.1 on 2026-08-29 00:43

from django.db import migrations, models


def assign_sort_order(apps, schema_editor):
    Folder = apps.get_model('bookmarks', 'Folder')
    Bookmark = apps.get_model('bookmarks', 'Bookmark')
    user_ids = set(Folder.objects.values_list('user_id', flat=True))
    user_ids.update(Bookmark.objects.values_list('user_id', flat=True))
    for user_id in user_ids:
        folders = list(Folder.objects.filter(user_id=user_id).order_by('name', 'pk'))
        unfiled = list(
            Bookmark.objects.filter(user_id=user_id, folder_id__isnull=True).order_by('title', 'pk')
        )
        for index, folder in enumerate(folders):
            folder.sort_order = index
            folder.save(update_fields=['sort_order'])
        offset = len(folders)
        for index, bookmark in enumerate(unfiled):
            bookmark.sort_order = offset + index
            bookmark.save(update_fields=['sort_order'])
        for folder in folders:
            for index, bookmark in enumerate(folder.bookmarks.order_by('title', 'pk')):
                bookmark.sort_order = index
                bookmark.save(update_fields=['sort_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0004_bookmark_title_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['sort_order', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['sort_order', 'pk']},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folder',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(assign_sort_order, migrations.RunPython.noop),
    ]



class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0004_bookmark_title_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['sort_order', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['sort_order', 'pk']},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folder',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
